name: Análise de Segurança com Semgrep

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  semgrep_scan:
    name: Semgrep SAST Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Executar Semgrep SAST Scan
        uses: returntocorp/semgrep-action@v1
        with:
          generateSarif: true
        continue-on-error: true

      - name: Upload do relatório SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
