name: Análise de Segurança com Semgrep 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  semgrep_scan:
    name: Semgrep SAST Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar Semgrep CLI
        run: pip install semgrep


      - name: Executar Scan do Semgrep
        run: semgrep scan --config "auto" --sarif -o semgrep.sarif
        continue-on-error: true 

      - name: Fazer Upload do relatório SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
