name: Pipeline DevSecOps

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  # JOB 1: Análises Estáticas (SAST e SCA)
  analise_estatica:
    name: Análise Estática (SAST + SCA)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # --- SAST ---
      - name: Instalar e Executar Semgrep (SAST)
        run: |
          pip install semgrep
          semgrep scan --config "auto" --sarif -o semgrep.sarif
        continue-on-error: true

      - name: Fazer Upload do relatório SAST
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif

      # --- SCA ---
      - name: Instalar e Executar OWASP Dependency-Check (SCA)
        run: |
          pip install dependency-check
          dependency-check --scan . --format "HTML" --project "Sprint-Cyber" --out reports
        continue-on-error: true # Continua mesmo se achar vulnerabilidades

      - name: Fazer Upload do relatório SCA
        uses: actions/upload-artifact@v3
        with:
          name: relatorio-sca
          path: reports/

  # JOB 2: Análise Dinâmica (DAST)
  analise_dinamica:
    name: Análise Dinâmica (DAST)
    runs-on: ubuntu-latest
    needs: analise_estatica # Só roda se o JOB 1 passar com sucesso

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Instalar dependências da aplicação
        run: pip install -r requirements.txt

      - name: Iniciar a aplicação em background
        run: python app.py &

      - name: Pausar por 15s para a aplicação iniciar
        run: sleep 15

      # --- DAST ---
      - name: Executar OWASP ZAP Baseline Scan (DAST)
        uses: zaproxy/action-baseline@v0.11.0
        with:
          # O target é a aplicação rodando na porta 5000
          target: 'http://localhost:5000/'
          # Gera um relatório em HTML
          cmd_options: '-J zap_report.html'
          
      - name: Fazer Upload do relatório DAST
        uses: actions/upload-artifact@v3
        with:
          name: relatorio-dast
          path: zap_report.html
