name: Análise de Segurança com Semgrep

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


# Este bloco concede ao pipeline a permissão necessária para fazer o upload dos resultados para a aba "Security".

permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  semgrep_scan:
    name: Semgrep SAST Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Executar Semgrep SAST Scan
        uses: returntocorp/semgrep-action@v1
        with:
          generateSarif: true

      - name: Upload do relatório SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
